MetaDataFormat: "yaml"

LanguageCode: "en-US"
BaseURL: "http://0.0.0.0:6789/"
Title: "AFAM"
Copyright: "AFAM"


Params:
    Domain: "afam.com"
    Publisher:
        Name: "AFAM"
        GoogleUserName: "afam"
        TwitterUserName: "afam"
    GoogleAnalyticsID: "UA-XXXXXXXX-X"
    DisqusShortname: "afam"
    Locales:
         - Code: "en-US"
           Name: "English"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "January 2, 2006"
    Social:
      Facebook: "afam"
      Twitter: "afam"
      TwitterDomain: "www.afam.com" # This domain shows in twitter cards as "View on 
      Googleplus: "afam"

    Authors:
      Henry:
        Name: "Henry Addo"
        Bio: "Software developer at Addhen Limited"
        Social:
          Github: "eyedol"
          Twitter: "eyedol"
    Widgets:
      RecentArticles: true
      Tags: true

    Location:
      Address: "Sumiyoshidia Higashi 4-13-12, Izumi-ku, Sendia, Miyagi, Japan"
      Telephone: "+81 22-376-4092"
      EmailAddress: "contact@afam.com"

Menu:
    Main:
        - Name: "Home"
          Weight: 0
          Identifier: "home"
        - Name: "About Us"
          Weight: 1
          Identifier: "about"
          URL: "about"
        - Name: "Constitution"
          Weight: 2
          Identifier: "constitution"
          URL: "constitution"
        - Name: "Calendar"
          Weight: 3
          Identifier: "calendar"
          URL: "calendar"
        - Name: "Join"
          Weight: 4
          Identifier: "join"
          URL: "join"
        - Name: "Contact Us"
          Weight: 5
          Identifier: "contact"
          URL: "#contact"
    External:
        - Name: "Facebook"
          Weight: 1
          Identifier: "facebook"
          URL: "https://facebook.com/afam"

Taxonomies:
    Tags: "tags"
