MetaDataFormat: "yaml"

LanguageCode: "en-US"
BaseURL: "http://www.addhen.com/"
Theme: "mdb-addhen"
Title: "Android Apps Development Company"
Copyright: "addhen limited"

Params:
    Domain: "addhen.com"
    Publisher:
        Name: "Addhen Limited"
        GoogleUserName: "addhen"
        TwitterUserName: "addhenltd"
    GoogleAnalyticsID: "UA-76734972-1"
    DisqusShortname: "addhen"
    Locales:
         - Code: "en-US"
           Name: "English"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "January 2, 2006"
    Social:
      Github: "addhen"
      Facebook: "addhenltd"
      Twitter: "addhenltd"
      TwitterDomain: "www.addhen.com" # This domain shows in twitter cards as "View on 
      Googleplus: "addhen"

    Authors:
      Henry:
        Name: "Henry Addo"
        Bio: "Software developer at Addhen Limited"
        Social:
          Github: "eyedol"
          Twitter: "eyedol"
          LinkedIn: "henryaddo"
    Widgets:
      RecentArticles: true
      Tags: true

Menu:
    Main:
        - Name: "Home"
          Weight: 0
          Identifier: "home"
          URL: "/"
        - Name: "What We Do"
          Weight: 1
          Identifier: "what-we-do"
          URL: "#what-we-do"
        - Name: "Portfolio"
          Weight: 2
          Identifier: "portfolio"
          URL: "#portfolio"
        - Name: "Contact Us"
          Weight: 3
          Identifier: "contact"
          URL: "#contact"
        - Name: "Blog"
          Weight: 4
          Identifier: "blog"
          URL: "/blog/"  
    External:
        - Name: "Google+"
          Weight: 1
          Identifier: "google-plus"
          URL: "https://plus.google.com/u/0/100985884362110852858"
        - Name: "Github"
          Weight: 2
          Identifier: "github"
          URL: "https://github.com/addhen"
        - Name: "Bitbucket"
          Weight: 3
          Identifier: "bitbucket"
          URL: "https://bitbucket.org/addhen"

Taxonomies:
    Tags: "tags"
