MetaDataFormat: "yaml"

ContentDir: "content/en-US"
PublishDir: "public/en-US"

LanguageCode: en-US
BaseURL: "https://zeeshell.com/en-US/"
Title: "ZeeShell"
Copyright: "ZeeShell Ltd"

Params:
    Domain: "zeeshell.com"
    Publisher:
        Name: "ZeeShell"
        GoogleUserName: "ZeeShell"
        TwitterUserName: "ZeeShell"
    BaseDir: "/en-US/"
    AlternateBaseDir: "/ja/"
    AlternateLangCode: "ja"
    GoogleAnalyticsID: "UA-37352183-2"
    Locales:
         - Code: "en-US"
           Name: "English"
         - Code: "ja"
           Name: "Japanese"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "Feburary 16, 2016"

Menu:
    Main:
        - Name: "What We Do"
          Weight: 0
          Identifier: "what-we-do"
          URL: "#what-we-do"
        - Name: "Portfolio"
          Weight: 1
          Identifier: "portfolio"
          URL: "#portfolio"
        - Name: "About"
          Weight: 2
          Identifier: "about"
          URL: "#about"
        - Name: "Contact"
          Weight: 3
          Identifier: "contact"
          URL: "#contact"
        - Name: "Blog"
          Weight: 4
          Identifier: "blog"
          URL: "/blog/"  
    External:
        - Name: "Feed"
          Weight: 0
          Identifier: "rss"
          URL: "/index.xml"
        - Name: "Twitter"
          Weight: 1
          Identifier: "twitter"
          URL: "https://twitter.com/eyedol"
        - Name: "Google+"
          Weight: 2
          Identifier: "google-plus"
          URL: "https://plus.google.com/+ZeeShell"
        - Name: "Bitbucket"
          Weight: 3
          Identifier: "bitbucket"
          URL: "https://bitbucket.org/zeeshell"