MetaDataFormat: "yaml"

ContentDir: "content/en-US"
PublishDir: "public/en-US"

LanguageCode: en-US
BaseURL: "https://zeeshell.com/en-US/"
Title: "addhen"
Copyright: "addhen Ltd"

Params:
    Domain: "addhen.com"
    Publisher:
        Name: "addhen"
        GoogleUserName: "addhen"
        TwitterUserName: "addhen"
    BaseDir: "/en-US/"
    AlternateBaseDir: "/ja/"
    AlternateLangCode: "ja"
    GoogleAnalyticsID: "<REPLACE With GA UA Code>"
    disqusShortname: "addhen"
    Locales:
         - Code: "en-US"
           Name: "English"
         - Code: "ja"
           Name: "Japanese"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "Feburary 16, 2006"

Menu:
    Main:
        - Name: "What We Do"
          Weight: 0
          Identifier: "what-we-do"
          URL: "#what-we-do"
        - Name: "Portfolio"
          Weight: 1
          Identifier: "portfolio"
          URL: "#portfolio"
        - Name: "Contact Us"
          Weight: 2
          Identifier: "contact"
          URL: "#contact"
        - Name: "Blog"
          Weight: 3
          Identifier: "blog"
          URL: "/blog/"  
    External:
        - Name: "Google+"
          Weight: 1
          Identifier: "google-plus"
          URL: "https://plus.google.com/u/0/100985884362110852858"
        - Name: "Github"
          Weight: 2
          Identifier: "github"
          URL: "https://github.com/addhen"
        - Name: "Bitbucket"
          Weight: 3
          Identifier: "bitbucket"
          URL: "https://bitbucket.org/addhen"