MetaDataFormat: "yaml"

ContentDir: "content/ja"
PublishDir: "public/ja"

LanguageCode: ja
BaseURL: "https://zeeshell.com/ja/"
Title: "ZeeShell Limited"
Copyright: "ZeeShell Ltd"

Author:
    Name: "Kohei Yoshino"
    Email: "webmaster@fxsitecompat.com"
    GoogleUserName: "KoheiYoshino"
    TwitterUserName: "koyoskeh"
    FacebookID: "100003919776216"
    FacebookUserName: "kohei.yoshino.aqr"

Params:
    Domain: "zeeshell.com"
    Publisher:
        Name: "ZeeShell"
        GoogleUserName: "ZeeShell"
        TwitterUserName: "ZeeShell"
    BaseDir: "/ja/"
    AlternateBaseDir: "/ja/"
    AlternateLangCode: "ja"
    GoogleAnalyticsID: "UA-37352183-2"
    GoogleSiteSearchID: "006388931142546140887:uidl4-zslfu"
    GoogleSiteSearchLangCode: "ja"
    Locales:
         - Code: "en-US"
           Name: "英語"
         - Code: "ja"
           Name: "日本語"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "2016 年 02 月 16 日"

Taxonomies:
    category: "categories"
    version: "versions"
    status: "statuses"

Menu:
    Main:
        - Name: "ホーム"
          Weight: 0
          Identifier: "home"
          URL: "/"
        - Name: "ブログ"
          Weight: 1
          Identifier: "blog"
          URL: "/blog/"
        - Name: "概要"
          Weight: 2
          Identifier: "about"
          URL: "/about/"
        - Name: "協力"
          Weight: 3
          Identifier: "contact"
          URL: "/contact/"
    External:
        - Name: "フィード"
          Weight: 0
          Identifier: "feed"
          URL: "/index.xml"
        - Name: "Twitter"
          Weight: 1
          Identifier: "twitter"
          URL: "https://twitter.com/FxSiteCompat"
        - Name: "Google+"
          Weight: 2
          Identifier: "google-plus"
          URL: "https://plus.google.com/+ZeeShell"
        - Name: "Bitbucket"
          Weight: 3
          Identifier: "bitbucket"
          URL: "https://bitbucket.org/zeeshell"